export const COUNTER1ADD = 'COUNTER1ADD';
export const COUNTER1MINUS = 'COUNTER1MINUS';
export const COUNTER2ADD = 'COUNTER2ADD';
export const COUNTER2MINUS = 'COUNTER2MINUS';
export const COUNTERRESET = 'COUNTERRESET';

